apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: infinispanbackups.infinispan.org
spec:
  group: infinispan.org
  names:
    kind: InfinispanBackup
    listKind: InfinispanBackupList
    plural: infinispanbackups
    singular: infinispanbackup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: InfinispanBackup is the Schema for the infinispanbackups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: InfinispanBackupSpec defines the desired state of InfinispanBackup
          type: object
        status:
          description: InfinispanBackupStatus defines the observed state of InfinispanBackup
          type: object
      type: object
  version: v2alpha1
  versions:
  - name: v2alpha1
    served: true
    storage: true
